### ISSUE TITLE
Research ML in Stock Price Analysis

### ISSUE THREAD

**Issue by fexolm** [team-stonks/stonks-api#2]

**Comment by Pythonimous** [comment]
01/25-01/31 EoW - researched ML applications in stock price analysis (.txt attached)
02/01-02/07 SoW - look for corpora and / or existing / pretrained solutions.
[ML in Stock price prediction.zip](https://github.com/team-stonks/stonks-api/files/5898411/ML.in.Stock.price.prediction.zip)

**Comment by Pythonimous** [comment]
Кирилл Николаев
